server:
  port: 8084


spring:
  main:
    web-application-type: reactive
  application:
    name: api-gateway
  zipkin:
      base-url: http://localhost:9411
  cloud:
    gateway:
      routes:
#        - id: customer
#          uri: lb://CUSTOMER
#          predicates:
#            - Path=/api/v1/customers/**

        - id: local
          uri: http://localhost:8085
          predicates:
            - Path=/api/v1/tourism/**

        - id: local
          uri: http://localhost:8087
          predicates:
            - Path=/api/v1/transport/**

        - id: local
          uri: http://localhost:8086
          predicates:
            - Path=/api/v1/accommodation/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders:
              - "*"
            allowCredentials: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

    fetch-registry: true
    register-with-eureka: true
    enabled: false