server:
  port: 8083

spring:
  profiles:
    active: default

  application:
    name: notification

  datasource:
    username: 'postgres'
    password: 'postgres'
    url: 'jdbc:postgresql://localhost:5433/notification'
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'true'
    hibernate:
      ddl-auto: update
    show-sql: 'true'
  zipkin:
    base-url: http://localhost:9411
  rabbitmq:
    addresses: localhost:5672

  mail:
    host: sandbox.smtp.mailtrap.io
    port: 587
    username: 0c5a4f244a1360
    password: c38cf4dff0de75
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
    enabled: false


rabbitmq:
  exchanges:
    internal: internal.exchange
  queues:
    notification: notification.queue
  routing-keys:
    internal-notification: internal.notification.routing-key